//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int ID { get; set; }
        public Nullable<int> ID_Student { get; set; }
        public Nullable<int> ID_Subject { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Visited { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
